backend:
  name: github
  repo: jucaserta/restauracaoeliberdade
  branch: main
  base_url: https://auth.restauracaoeliberdade.com.br
  auth_endpoint: auth.php

media_folder: "public/uploads"
public_folder: "/uploads"

collections: []
