backend:
  name: github
  repo: jucaserta/restauracaoeliberdade
  branch: main
  site_domain: restauracaoeliberdade.com.br
  base_url: https://restauracaoeliberdade.com.br
  auth_endpoint: /api/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/index.astro"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
