backend:
  name: github
  repo: jucaserta/restauracaoeliberdade
  branch: main
  base_url: https://auth.restauracaoeliberdade.com.br
  auth_endpoint: auth.php

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "theme"
    label: "Tema (Astro)"
    files:
      - label: "Home (src/pages/index.astro)"
        name: "home"
        file: "src/pages/index.astro"
        format: "raw"
        fields:
          - label: "C贸digo"
            name: "body"
            widget: "code"
            default_language: "astro"

      - label: "Layout Base (src/layouts/Base.astro)"
        name: "base_layout"
        file: "src/layouts/Base.astro"
        format: "raw"
        fields:
          - label: "C贸digo"
            name: "body"
            widget: "code"
            default_language: "astro"

      - label: "Header (src/components/Header.astro)"
        name: "header"
        file: "src/components/Header.astro"
        format: "raw"
        fields:
          - label: "C贸digo"
            name: "body"
            widget: "code"
            default_language: "astro"

      - label: "Footer (src/components/Footer.astro)"
        name: "footer"
        file: "src/components/Footer.astro"
        format: "raw"
        fields:
          - label: "C贸digo"
            name: "body"
            widget: "code"
            default_language: "astro"
