backend:
  name: github
  repo: jucaserta/restauracaoeliberdade
  branch: main
  base_url: https://auth.restauracaoeliberdade.com.br
  auth_endpoint: auth.php

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
